In [1]:
import pandas as pd
import numpy as np
print('setup complete')

setup complete


In [2]:
ar1 = np.arange(2,20,2).reshape(3,3)

In [3]:
ar1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [4]:
ar2 = ar1 + 1
ar2

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [5]:
np.concatenate([ar1, ar2])

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [6]:
np.concatenate([ar1, ar2], axis=1)

array([[ 2,  4,  6,  3,  5,  7],
       [ 8, 10, 12,  9, 11, 13],
       [14, 16, 18, 15, 17, 19]])

In [7]:
ser1 = pd.Series(np.random.rand(3), index=[1,2,3])
ser1

1    0.455823
2    0.375191
3    0.228952
dtype: float64

In [8]:
ser2 = pd.Series(np.random.rand(3), index=[4,5,6])
ser2

4    0.96068
5    0.21441
6    0.97615
dtype: float64

In [9]:
pd.concat([ser1, ser2])

1    0.455823
2    0.375191
3    0.228952
4    0.960680
5    0.214410
6    0.976150
dtype: float64

In [10]:
pd.concat([ser1, ser2], axis=1)

0        1
1  0.455823      NaN
2  0.375191      NaN
3  0.228952      NaN
4       NaN  0.96068
5       NaN  0.21441
6       NaN  0.97615

In [13]:
pd.concat([ser1, ser2], keys=[1,2])

1  1    0.455823
   2    0.375191
   3    0.228952
2  4    0.960680
   5    0.214410
   6    0.976150
dtype: float64

In [14]:
pd.concat([ser1, ser2], keys=[1,2],axis=1)

1        2
1  0.455823      NaN
2  0.375191      NaN
3  0.228952      NaN
4       NaN  0.96068
5       NaN  0.21441
6       NaN  0.97615

In [15]:
df1 = pd.DataFrame(ar1, index=[1,2,3],columns=['A','B','C'])
df1

A   B   C
1   2   4   6
2   8  10  12
3  14  16  18

In [16]:
df2 = pd.DataFrame(ar2, index=[4,5,6],columns=['A','B','C'])
df2

A   B   C
4   3   5   7
5   9  11  13
6  15  17  19

In [17]:
pd.concat([df1,df2])

A   B   C
1   2   4   6
2   8  10  12
3  14  16  18
4   3   5   7
5   9  11  13
6  15  17  19

In [18]:
pd.concat([df1,df2],axis=1)

A     B     C     A     B     C
1   2.0   4.0   6.0   NaN   NaN   NaN
2   8.0  10.0  12.0   NaN   NaN   NaN
3  14.0  16.0  18.0   NaN   NaN   NaN
4   NaN   NaN   NaN   3.0   5.0   7.0
5   NaN   NaN   NaN   9.0  11.0  13.0
6   NaN   NaN   NaN  15.0  17.0  19.0

In [19]:
df3 = pd.DataFrame(ar2, index=[2,3,4],columns=['A','B','C'])
df3

A   B   C
2   3   5   7
3   9  11  13
4  15  17  19

In [20]:
pd.concat([df1,df3])

A   B   C
1   2   4   6
2   8  10  12
3  14  16  18
2   3   5   7
3   9  11  13
4  15  17  19

In [21]:
try: pd.concat([df1,df3], verify_integrity=True)
except ValueError as e: print("ValueError:",e)

ValueError: Indexes have overlapping values: Int64Index([2, 3], dtype='int64')
